name: Update status
on: 
  push:
    branches:
      - main
  schedule:
    - cron:  '52 * * * *'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Run surge-status.sh
        run: sh ./surge-status.sh
        shell: bash

      - name: Push README.md
        run: |
          git add README.md
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config user.name "GitHub Actions[Bot]"
          if [[ $(git status --porcelain "README.md" | wc -l) -gt 0 ]]; then git commit -m "[BOT] Update README.md"; git push; fi
